- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL
    ansible.builtin.dnf:
    - name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install ubuntu
    ansible.builtin.apt:
    - name: ubuntu
      state: installed
    when: ansible_os_family == "Debian"  