- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "hello {{person | default('Sriram')}}"

  - name: convert string to list
    vars:
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "fruits are:{{fruits | split(',')}}"

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: krishna
    ansible.builtin.debug:
      msg: "Coure details are:{{course | dict2items}}"    

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'krishna'}
    ansible.builtin.debug:
      msg: "course info:{{course | items2dict}}"  

  - name: convert upper to lower
    vars:
      name: "Sri Ram" 
    ansible.builtin.debug:
      msg: "{{ name| lower }}"    
  - name: convert lower to upper
    vars:
      name: "Sri Ram"
    ansible.builtin.debug:
      msg: "{{ name| upper}}"   
      
  - name: print min and max
    vars:
      num: [23,43,12,54,1,89,32]
    ansible.builtin.debug:
      msg: "Mai is: {{num|max}},min is:{{num|min}}"  

  - name: check ipaddress is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"    
     
