- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "hello {{person | default('Sriram')}}"

  - name: convert string to list
    vars:
      fruits: "apple,banana,orange"
    ansible.builtin.debug:
      msg: "fruits are:{{fruits | split(',')}}"

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: krishna
    ansible.builtin.debug:
      msg: "Coure details are:{{course | dict2items}}"    
